### PR TITLE
Reuse test.sh under Travis and fixe failing test

### PR DESCRIPTION
**Pull request by chalin**
Now running the more complete `test.sh` under Travis (actually script has been renamed to `tool/build_and_test.sh` since it built and tested :). Keeping `test.sh` as alias to `build_and_test.sh` in case people are used to using it in the test directory.

Also removed `_visitOrEmpty` to resolve the following analyzer hint (so that tests would pass):
> [hint] The method '_visitOrEmpty' is not used (/Users/chalin/git/dev_compiler/lib/src/codegen/js_codegen.dart, line 2028, col 16)

Addresses the question in https://github.com/dart-lang/dev_compiler/pull/111#issuecomment-87032810
> btw - do we know why we can't call test.sh in travis?

### CODE REVIEW

**Comment by jmesserly** [comment]
curious about the rename test/test.sh -> tool/build_and_test.sh, any idea why it shows the entire thing as a diff? I can pull it down and diff manually, but odd that git didn't track detect that.

the "build_and_test" name seems a bit long, maybe just have travis.yml run the three (build_sdk.sh, test.sh, coverage.sh) in sequence? We could then rename test/test.sh -> tool/presubmit.sh and instruct folks to run presubmit.sh first :)

By the way, I'm happy to merge this and make these changes, just wanted to run them by you first. Thanks so much for taking the time to do this!

**Comment by jmesserly** [comment]
fwiw, the diff was just:
```diff
@@ -24,11 +24,9 @@ function show_diff {
   fail
 }
 
-# the directory of this script
-TEST_DIR=$( cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )
-
 # Some tests require being run from the package root
-cd $TEST_DIR/..
+# switch to the root directory of dev_compiler
+cd $( dirname "${BASH_SOURCE[0]}" )/..
 
 # Check minimum SDK version
 ./tool/sdk_version_check.dart 1.9.0-dev.4.0 || fail
@@ -77,6 +75,5 @@ dartanalyzer --fatal-warnings --package-warnings bin/devc.dart | (! grep $PWD) \
   tool/*.dart | grep -v lib/src/js/`; git status -s $files | grep -q . \
   && echo "Did not run the formatter, please commit edited files first." \
   || (echo "Running dart formatter" ; pub run dart_style:format -w $files))
-popd &> /dev/null

```

**Comment by jmesserly** [comment]
going to go ahead and merge. thanks!

**Comment by jmesserly** [comment]
hmmm, this seemed to cause a break on Travis, which is really strange because it worked before. It looks like some files got generated because of code coverage mode, which we didn't expect to be there when we diff'd against expected output. Reverting temporarily to figure out the best fix

**Comment by jmesserly** [comment]
trying to re-land this, CL is here (I personally like pull requests but some other team members prefer Rietveld): https://codereview.chromium.org/1042863004/

**Comment by jmesserly** [comment]
landed as https://github.com/dart-lang/dev_compiler/commit/529cfd61c735ff5047885f68398c97ad3d43b26a
let me know if those names seem good

**Comment by chalin** [comment]
Good rework/renaming. Sorry for the extra effort that involved.

**Comment by jmesserly** [comment]
no problem. Appreciate your help on this. The new set up using the "tool/" directory is a lot nicer :)

**Pull request merged**
