### PR TITLE
Run coverage, transformer and node tests in their own Travis env

### PR DESCRIPTION
**Pull request by ochafik**
See output https://travis-ci.org/dart-lang/dev_compiler/builds/112786293

### CODE REVIEW

**Comment by vsmenon** [comment]
Very cool!  Do you know why coverage is timing out?

**Comment by vsmenon** [comment]
Can you try rebasing?  My recent html extension CL sped up tests by a good bit, so maybe avoiding the timeout - I hope!

The hello app should be fixed now as well.

**Comment by ochafik** [comment]
Wow, the extension type change [halved the travis execution time](https://travis-ci.org/dart-lang/dev_compiler/builds/113024377)!

And... coverage ends in finite time!

The hello_app still seems broken, though (does `pub run test test/transformer_e2e_test.dart` work locally for you?).

**Comment by vsmenon** [comment]
lgtm

Great!  I'm still getting this on the e2e test locally though:

```
Bad state: Pub get failed: The pubspec for dev_compiler 0.1.17 from path has version 0.1.21.
```

**Pull request merged**
