### PR TITLE
fixes #109, code coverage for SDK generation

### LINKED ISSUE #109: code coverage no longer including SDK compile
it was my change here:
https://coveralls.io/builds/2159520

... because it's not part of all_tests it's not included in coverage. The coverage report for js_codegen.dart is now rather misleading, as everything covered by the SDK build is not counted.

### PR DESCRIPTION
**Pull request by jmesserly**

### CODE REVIEW

**Comment by jmesserly** [comment]
@vsmenon @kevmoo mind taking a look? here's the coverage report, it's +8% wtih this changehttps://coveralls.io/builds/2207764

**Comment by jmesserly** [comment]
reason I noticed: was happy to have gotten js_codegen was 97% ... but then noticed it had dropped to 81%. ouch :)

**Comment by kevmoo** [comment]
@jmesserly I'm confused. What do you want us to look at?

**Comment by jmesserly** [comment]
I was hoping for a code review, per our usual code review policy. :)

**Comment by kevmoo** [comment]
LGTM! :smile:

**Pull request merged**
