### PR TITLE
reorganize SDK inputs

### PR DESCRIPTION
**Pull request by jmesserly**
it's all under input_sdk now:
* lib -> the lib folder
* private -> the dart:_* libs
* patch -> the files with `@patch`

I imagine we'll try and focus changes on the last two

@vsmenon -- do you mind reviewing this? I tried [a Rietveld CL](https://codereview.chromium.org/969233002/), but it doesn't handle changes like this well (tries to upload all the baselines and such ... whereas git understands it's just a bunch of moves).

### CODE REVIEW

**Comment by sigmundch** [comment]
FYI - the `A+` next to a file in Rietvelt (as opposed to a plain `A`), seems to preserve the blame information (similar to doing a file move, rather than a file add + delete). For example, my change here:
https://github.com/dart-lang/dev_compiler/commit/9bea258f69469a2a23395701d2dcac4ac1227780

seems to have preserved the blame from before the move (for instance, on this file: https://github.com/dart-lang/dev_compiler/blame/master/test/dart_codegen/expect/convert/convert)

The history does not include older changes though: https://github.com/dart-lang/dev_compiler/commits/master/test/dart_codegen/expect/convert/convert

**Comment by jmesserly** [comment]
yeah, it keeps the blame (good) but it takes minutes to upload and is super flaky (bad). `git push origin sdk` was like 1 second. Plus, scanning through the files on GitHub takes like a few seconds to see nothing changed. Compare to paging through all hundred of those non-changes in Rietveld. I mean, feel free to review it there if you really prefer, but I can't promise further uploads to that CL :)

**Comment by sigmundch** [comment]
Oh, yeah, I was just clarifying about the move, I think you are totally right, this is a lot better for this kind of changes anyways :)

LGTM

**Comment by jmesserly** [comment]
thanks siggi :+1:

**Comment by jmesserly** [comment]
funny, git on the command line actually formats these the best :)
```
 rename tool/{input_sdk_src => input_sdk}/lib/typed_data/typed_data.dart (100%)
 rename tool/{input_sdk_patch => input_sdk/patch}/async_patch.dart (100%)
 rename tool/{input_sdk_src/lib/_internal/compiler/js_lib => input_sdk/private}/annotations.dart (100%)
```

I like how it shows which part of the path changed

**Pull request merged**
