### PR TITLE
run build_sdk.sh from travis

### PR DESCRIPTION
**Pull request by jmesserly**
this is done by our test.sh script, but we aren't covering it

### CODE REVIEW

**Comment by jmesserly** [comment]
@vsmenon mind taking a look? fyi -- it passed, see https://travis-ci.org/dart-lang/dev_compiler/builds/56107620

**Comment by sigmundch** [comment]
lgtm

btw - do we know why we can't call test.sh in travis?

**Comment by jmesserly** [comment]
> btw - do we know why we can't call test.sh in travis?

not sure. Maybe @kevmoo knows?

**Comment by chalin** [comment]
> btw - do we know why we can't call test.sh in travis?

We can :). #114 makes use of `test.sh` on Travis. `test.sh` ran fine after removing an extra `popd`. One test was failing though due to an analyzer hint not being addressed, that was fixed too.

**Pull request merged**
