### PR TITLE
normalize lib/ self-refs to path references

### PR DESCRIPTION
**Pull request by devoncarew**
Related to https://github.com/dart-lang/dev_compiler/issues/331, normalize lib/ self-refs to path references. This reduces the number of issues analyzing the ddc with itself from 344 to 288.

Happy to discard this if you guys prefer `package:dev_compiler/...` refs. You'll probably want to convert the path refs in `lib/` to package: refs in that case -

### CODE REVIEW

**Comment by jmesserly** [comment]
I'm confused by this.... normalizing should not be necessary. Analyzer has no issues.

@sigmundch @munificent @nex3 -- didn't we have a convention that required avoiding ".."? As I understood it:

* use package:foo/bar.dart instead of "../bar.dar"
* otherwise, relative paths are acceptable, e.g. "src/baz.dart" instead of "package:foo/src/baz.dart"

Help me remember how this rule came about?

**Comment by jmesserly** [comment]
ah, I now see #331. Personally ... I'd rather fix that bug in the error reporting rather than change the reference style of the code to work around it...

**Comment by devoncarew** [comment]
> Personally ... I'd rather fix that bug in the error reporting rather than change the reference style of the code

Makes sense! Will close this out.

**Comment by sigmundch** [comment]
As far as the convention goes: that was what I thought, or at least what we've been doing since webui and polymer. I believe Natalie prefers relative ../ paths. I currently prefer the other convention because otherwise users make the leap of trying to access outside the `lib` folder via `../../` (this was the case in the dart2js compiler package, for example).

I'd be ok using the `../` convention if we could add some hints, maybe in analyzer and/or in pub-lish, to detect if you reached out of your lib folder, and hence you should not expect your code to work as a package if you were to publish it.

thoughts?

**Comment by jmesserly** [comment]
hmmm, now that I'm playing with analyzer, it seems like having only relative URIs inside your own package gives it an easier time of analyzing "lib/..."  otherwise you can't point analyzer straight at those files, or it will think the file:// URIs are different libraries.

@vsmenon @leafpetersen thoughts on changing our convention to use "../" in DDC code?

**Comment by nex3** [comment]
We talked about this in person, but for posterity my style is to always use relative imports for importing within a single `lib/` directory, whether they start with `../` or not.

**Comment by jmesserly** [comment]
I think we're good on "../" too. (IIRC we haven't yet had an issue on dev_compiler with incorrect bin/ or test/ imports)

**Comment by jmesserly** [comment]
Thanks Devon for the pull req & everyone for helping think through the tradeoffs

**Comment by munificent** [comment]
My guideline is to use "package:" any time any import crosses into our out of a `lib/` directory. Otherwise, I use relative.

**Pull request merged**
