### PR TITLE
Fix compilation of `x ~/ y` (use Math.trunc instead of hitting Number.truncate())

### PR DESCRIPTION
**Pull request by ochafik**
….truncate())

### CODE REVIEW

**Comment by jmesserly** [comment]
good catch! I think it was supposed to be calling the Dart `truncate` method, but was never fixed to do that: https://github.com/dart-lang/dev_compiler/blob/master/tool/input_sdk/private/js_number.dart#L78

but yeah, we could definitely merge this as it's a big improvement over current behavior.

 calling truncate would be `(a / b)[dartx.truncate]()`, so probably something like this in js_codegen:
```dart
var div = AstBuilder.binaryExpression(left, '/', right);
return _emitSend(div, 'truncate', []);
```

anyway I can file a bug to fix that.

**Comment by jmesserly** [comment]
oh, btw, if you don't mind, could you run ./tool/presumbit.sh? I think test/codegen/expect/DeltaBlue.js and test/codegen/expect/expect.js will automatically update to show the new code (it looks like the Travis bot isn't catching this)

**Comment by jmesserly** [comment]
landed fix in https://github.com/dart-lang/dev_compiler/commit/e1cfec0d483bed6db7b061d7cb85cd1601b090e1, thanks again for catching this!

**Comment by ochafik** [comment]
Thanks for the proper fix John!

**Pull request closed without merging**
