### PR TITLE
Less dart.notNull checks for local vars using flow-insensitive nullability inference.

### PR DESCRIPTION
**Pull request by ochafik**
Less dart.notNull checks for local vars using flow-insensitive nullability inference.

Within some AST context (at library granularity, for convenience), we
collect all the assignments to local vars:
- Declaration with no initializer amounts to `null` assignment
- Assignment ops are expanded naively: `x++` yield an assigned value of
`x + 1`, etc

We detect "trivially nullable" variables (e.g. `var x;`, `x =
breaking.out;`) by spotting assigned values that are nullable under the
optimistic assumption that all known variables are non-nullable.

Then we build a nullability dependency graph in linear time: whenever
we see `x = y;`, we know that "y is nullable" implies "x is nullable".

Finally, we propagate "trivial nullabilities" through that graph: any
variable that wasn't reached is deemed not-nullable.

(this is similar to mark and sweep garbage collection, where the roots
are the "trivially nullable" variables; credits to leafpetersen@ for
linear solution)

(LGTM'd in [this review thread](https://codereview.chromium.org/1508963005))

### CODE REVIEW

**Comment by jmesserly** [comment]
Just curious, did you have a problem with "git cl land"?

**Comment by ochafik** [comment]
Yes, got a mergepocalypse... `git cl land [origin/master]` pretended there was no diff (`nothing to commit, working directory clean`), and it seems my target ref was wrong... Maybe because I followed the following advise after an first cl land attempt?
```
git cl land
Using 50% similarity for rename/copy detection. Override with --similarity.
Base branch "refs/remotes/origin/master" has 2 commits not in this branch.
Run "git merge refs/remotes/origin/master" before attempting to land.
```

**Comment by jmesserly** [comment]
I do "git fetch && git merge origin/master", never had any problems previously. I wonder what "git diff origin/master" showed at that point?

**Comment by ochafik** [comment]
Ah! I've been abusing `git fetch && git rebase -i origin/master`... I'll stop squashing from now on... (until I've read the full git manual ;-)).
Thanks!

**Comment by jmesserly** [comment]
Ohhhh, yeah, that makes sense! Squashing is a workflow for doing pull requests, definitely works, but it can lead to more conflicts especially if you're iterating and keeping up with other changes. I try and use "merge" as much as possible (it's smarter about ... merging :) ), and only squash at the very end. And "git cl land" will squash for you -- one of its more useful features. :)

**Pull request merged**
